// herbsy-frontend/src/lib/components/header.svelte
<script>
	import logo from '$lib/assets/logo.svg';
	
	let searchQuery = '';
	let searchResults = [];
	let showResults = false;

	// Simulate search - replace with actual API call later
	function handleSearch() {
		if (searchQuery.trim().length < 2) {
			searchResults = [];
			showResults = false;
			return;
		}

		// Mock data - replace with actual search API
		searchResults = [
			{ type: 'herb', name: 'Basil', url: '/herbs/basil' },
			{ type: 'spice', name: 'Cinnamon', url: '/spices/cinnamon' },
			{ type: 'product', name: 'Basil Essential Oil', url: '/shop/basil-oil' },
			{ type: 'blog', name: 'Benefits of Basil', url: '/blog/benefits-of-basil' }
		].filter(item => 
			item.name.toLowerCase().includes(searchQuery.toLowerCase())
		);
		
		showResults = true;
	}

	function handleInputChange() {
		handleSearch();
	}

	function closeResults() {
		setTimeout(() => {
			showResults = false;
		}, 200); // Delay to allow click on result
	}

	function selectResult(url) {
		searchQuery = '';
		searchResults = [];
		showResults = false;
		// Navigation happens via the <a> tag
	}
</script>

<div class="header">
	<a href="/" class="title-link">
		<img src={logo} class="logo" alt="Herbsy Logo" />
		<div class="title">Herbsy</div>
	</a>

	<!-- Search Form -->
	<div class="search-container">
		<form on:submit|preventDefault={handleSearch} class="search-form">
			<input
				type="text"
				bind:value={searchQuery}
				on:input={handleInputChange}
				on:focus={() => searchQuery && (showResults = true)}
				on:blur={closeResults}
				placeholder="Search herbs, spices, products..."
				class="search-input"
			/>
			<!-- svelte-ignore a11y_consider_explicit_label -->
			<button type="submit" class="search-button">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<circle cx="11" cy="11" r="8"></circle>
					<path d="m21 21-4.35-4.35"></path>
				</svg>
			</button>
		</form>

		<!-- Search Results Dropdown -->
		{#if showResults && searchResults.length > 0}
			<div class="search-results">
				{#each searchResults as result}
					<a href={result.url} class="search-result-item" on:click={() => selectResult(result.url)}>
						<span class="result-type">{result.type}</span>
						<span class="result-name">{result.name}</span>
					</a>
				{/each}
			</div>
		{:else if showResults && searchQuery.trim().length >= 2}
			<div class="search-results">
				<div class="no-results">No results found</div>
			</div>
		{/if}
	</div>

	<div class="menu">
		<a class="menu-link" href="/blog">Blog</a>
		<a class="menu-link" href="/shop">Shop</a>
		<a class="menu-link" href="/herbs">Herbs</a>
		<a class="menu-link" href="/spices">Spices</a>
	</div>

	<div class="others">
		<button>Create Account</button>
	</div>
</div>

<style>
	.header {
		border-bottom: 1px solid #ccc;
		color: black;
		padding: 20px 90px;
		display: flex;
		justify-content: space-between;
		align-items: center;
		gap: 2rem;
        box-shadow: 0 0 transparent, 0 0 transparent, 0 4px 8px rgba(0, 0, 0, .16);
	}

	.title-link {
		text-decoration: none;
		color: black;
		display: flex;
		align-items: center;
		gap: 0.5rem;
		flex-shrink: 0;
	}

	.title {
		font-size: 1.25rem;
		font-weight: bold;
		cursor: pointer;
		text-decoration: none;
	}

	.logo {
		width: 30px;
		height: 30px;
	}

	/* Search Styles */
	.search-container {
		position: relative;
		flex: 1;
		max-width: 400px;
	}

	.search-form {
		display: flex;
		position: relative;
	}

	.search-input {
		width: 100%;
		padding: 10px 40px 10px 16px;
		border: 1px solid #ccc;
		border-radius: 24px;
		font-size: 0.9rem;
		outline: none;
		transition: border-color 0.2s;
	}

	.search-input:focus {
		border-color: #4caf50;
	}

	.search-button {
		position: absolute;
		right: 8px;
		top: 50%;
		transform: translateY(-50%);
		background: none;
		border: none;
		color: #666;
		cursor: pointer;
		padding: 6px;
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 50%;
		transition: background-color 0.2s;
	}

	.search-button:hover {
		background-color: #f0f0f0;
	}

	.search-results {
		position: absolute;
		top: calc(100% + 8px);
		left: 0;
		right: 0;
		background: white;
		border: 1px solid #ccc;
		border-radius: 8px;
		box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
		max-height: 400px;
		overflow-y: auto;
		z-index: 1000;
	}

	.search-result-item {
		display: flex;
		align-items: center;
		gap: 12px;
		padding: 12px 16px;
		text-decoration: none;
		color: black;
		border-bottom: 1px solid #f0f0f0;
		transition: background-color 0.2s;
	}

	.search-result-item:last-child {
		border-bottom: none;
	}

	.search-result-item:hover {
		background-color: #f9f9f9;
	}

	.result-type {
		background-color: #4caf50;
		color: white;
		padding: 4px 8px;
		border-radius: 4px;
		font-size: 0.75rem;
		text-transform: uppercase;
		font-weight: 600;
	}

	.result-name {
		font-size: 0.95rem;
	}

	.no-results {
		padding: 16px;
		text-align: center;
		color: #666;
		font-size: 0.9rem;
	}

	.menu {
		display: flex;
		gap: 1rem;
		flex-shrink: 0;
	}

	.menu-link {
		text-decoration: none;
		color: black;
		font-size: 1rem;
	}

	.menu-link:hover {
		text-decoration: underline;
	}

	.others {
		flex-shrink: 0;
	}

	.others button {
		padding: 8px 16px;
		background-color: #4caf50;
		color: white;
		border: none;
		border-radius: 4px;
		cursor: pointer;
	}

	.others button:hover {
		background-color: #45a049;
	}
</style>

// frontend/src/components/Header/header.jsx
import React from "react";
import { Link } from "react-router-dom";
import logo from "../../images/logo.svg";

const Header = () => {
  return (
    <header>
      <nav className="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800 shadow-md">
        <div className="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
          <a
            href="/"
            className="flex items-center justify-center mb-1 text-2xl font-semibold text-gray-900 dark:text-white"
          >
            <img className="w-8 h-8 mr-2" src={logo} alt="logo" />
            Herbsy
          </a>
          <div className="flex items-center lg:order-3">
            <Link
              to="/signin"
              className="text-gray-700 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg  px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800"
            >
              Sign In
            </Link>
        
            <button
              data-collapse-toggle="mobile-menu-2"
              type="button"
              className="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
              aria-controls="mobile-menu-2"
              aria-expanded="false"
            >
              <span className="sr-only">Open main menu</span>
              <svg
                className="w-6 h-6"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fill-rule="evenodd"
                  d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                  clip-rule="evenodd"
                ></path>
              </svg>
              <svg
                className="hidden w-6 h-6"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fill-rule="evenodd"
                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                  clip-rule="evenodd"
                ></path>
              </svg>
            </button>
          </div>
          <div
            className="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1"
            id="mobile-menu-2"
          >
            <ul className="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
              <li>
                <Link
                  to="/"
                  className="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-green-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                >
                  Shop
                </Link>
              </li>
              <li>
                <Link
                  to="/"
                  className="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-green-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                >
                  Blog
                </Link>
              </li>
              <li>
                <Link
                  to="/"
                  className="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-green-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                >
                  Herbs
                </Link>
              </li>
              <li>
                <Link
                  to="/"
                  className="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-green-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                >
                  Spices
                </Link>
              </li>
            </ul>
          </div>
          <form className=" lg:order-2 w-80">
            <label
              for="default-search"
              className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white"
            >
              Search
            </label>
            <div className="relative">
              <div className="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                <svg
                  className="w-4 h-4 text-gray-500 dark:text-gray-400"
                  aria-hidden="true"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 20 20"
                >
                  <path
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
                  />
                </svg>
              </div>
              <input
                type="search"
                id="default-search"
                className="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-green-500 focus:border-green-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-green-500 dark:focus:border-green-500"
                placeholder="Search Herbs, Spices.."
                required
              />
              <button
                type="submit"
                className="text-white absolute end-2.5 bottom-2.5 bg-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800"
              >
                Search
              </button>
            </div>
          </form>
        </div>
      </nav>
    </header>
  );
};

export default Header;
